version: '3'
services:
  streamlit:
    image: senthilnathanl/streamlit
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - USER_BUCKET_NAME=${USER_BUCKET_NAME}

    ports:
      - "8000:8000"
  fastapi:
    image: senthilnathanl/fastapi
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - USER_BUCKET_NAME=${USER_BUCKET_NAME}
      - SECRET_KEY=${JWT_SECRET_KEY}

    volumes:
      - ./application/key.json:/fastapi/key.json
    ports:
      - "8080:8080"